services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=todo'
      - 'MARIADB_PASSWORD=1234'
      - 'MARIADB_ROOT_PASSWORD=1234'
      - 'MARIADB_USER=otteu'
    ports:
      - '3366:3306'
