spring:
  application:
    name: todo

  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false   # 실무 권장
    hibernate:
      ddl-auto: update   # local: update / prod: validate
#      dialect: org.hibernate.dialect.MariaDBDialect

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul

  servlet:
    multipart:
      max-request-size: 30MB
      #  한 파일의 크기 제한
      max-file-size: 10MB

org:
  zerock:
    upload:
      path: upload  
        
logging:
  level:
    org:
      springframework:
        security:
          web: TRACE